name: Deploy to EC2 using Ansible

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Configure EC2 via Ansible
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        # Write the private key into firstkey.pem
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/firstkey.pem
        chmod 600 ~/.ssh/firstkey.pem

    - name: Add EC2 host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Run Ansible Playbook
      run: |
        sudo apt update
        sudo apt install -y ansible
        ansible-playbook ansible/install_docker.yml -i ansible/inventory.ini
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
